initial test
naps-dev/dco-foundation pull request #22
Opened 2023-03-14 19:41 UTC by Vandiver247

2023-03-17 21:21 UTC, Vandiver247 commented
This pull req adds Kyverno to DCO Foundation. It does not add it to DCO Minimal as most of the important packages needed to support Kyverno are missing from Minimal.

This pull req also restructures and adds to the pipeline for DCO Foundation and DCO Foundation Minimal to bring them more closely in line with our other packages and support future testing automation.

2023-03-20 01:30 UTC, mikevanhemert requested changes
Looks good. A couple of minor happy-to-glad change requests.

Why are dco-foundation and dco-foundation-minimal separate tests? The TerraTest is 95% similar. We could pass in an env var specifying whether it's the full package or the minimal package to be a little more DRY.

Separate question: does the minimal package really make sense anymore? It was a convenience for folks testing locally (because it's smaller) but the application pipelines don't care.

2023-03-20 01:30 UTC, mikevanhemert commented on .github/workflows/main.yaml
> +  S3_PATH: "s3://${{ secrets.AWS_BUCKET }}/${{ github.repository }}/${{ github.head_ref || github.ref_name }}"
S3_PATH isn't used by package.yaml, it is overwritten there. We can remove it from this file

2023-03-20 01:30 UTC, mikevanhemert commented on .github/workflows/main.yaml
> +      S3_PATH: ${{ env.S3_PATH }}
Remove

2023-03-20 01:30 UTC, mikevanhemert commented on .github/workflows/main.yaml
> +      S3_PATH: ${{ needs.propagate-env.outputs.S3_PATH }}
Remove

2023-03-20 01:30 UTC, mikevanhemert commented on .github/workflows/package.yaml
> +      S3_PATH:
Remove, it's overwritten on line 25

2023-03-20 03:41 UTC, mikevanhemert commented on test/dco_foundation_test.go
> +        Args:    []string{"package", "deploy", "../zarf-package-dco-foundation-amd64.tar.zst", "--confirm"},
The branch should be passed in to `zarf package deploy` as `"--set", "BRANCH="+gitBranch` (from line 12)

2023-03-20 03:41 UTC, mikevanhemert commented on test-minimal/dco_foundation_minimal_test.go
> +        Args:    []string{"init", "--components", "git-server", "--confirm"},
The branch should be passed in to zarf package deploy as "--set", "BRANCH="+gitBranch (from line 12)

2023-03-20 12:55 UTC, Vandiver247 commented on .github/workflows/main.yaml
> +  S3_PATH: "s3://${{ secrets.AWS_BUCKET }}/${{ github.repository }}/${{ github.head_ref || github.ref_name }}"
I would argue we actually do it the opposite way around and remove it from package.yaml. The intent is to set everything consistently in main.yaml so if we end up with more tests and files, the same value is always passed.

2023-03-20 13:45 UTC, Vandiver247 commented on .github/workflows/package.yaml
> +      S3_PATH:
Leaving per my comment about leaving environment variable setting to main instead of package

2023-03-20 13:45 UTC, Vandiver247 commented on test/dco_foundation_test.go
> +        Args:    []string{"package", "deploy", "../zarf-package-dco-foundation-amd64.tar.zst", "--confirm"},
Updated

2023-03-20 13:45 UTC, Vandiver247 commented on test-minimal/dco_foundation_minimal_test.go
> +        Args:    []string{"init", "--components", "git-server", "--confirm"},
Updated

2023-03-20 13:48 UTC, mikevanhemert commented on .github/workflows/main.yaml
> +  S3_PATH: "s3://${{ secrets.AWS_BUCKET }}/${{ github.repository }}/${{ github.head_ref || github.ref_name }}"
It will fail; we cannot pass a value from secrets between workflow files

2023-03-20 16:35 UTC, Vandiver247 commented on .github/workflows/main.yaml
> +  S3_PATH: "s3://${{ secrets.AWS_BUCKET }}/${{ github.repository }}/${{ github.head_ref || github.ref_name }}"
fixed

2023-03-20 19:40 UTC, mikevanhemert approved these changes
Well done!

2023-03-20 19:49 UTC, merged