Tag usage update
naps-dev/dco-foundation pull request #24
Opened 2023-03-27 20:27 UTC by Vandiver247

Update to allow the usage of either tags or branch names during deployment.

2023-03-30 02:12 UTC, mikevanhemert requested changes
Functionally verified deployment works as expected when setting the BRANCH or TAG. I love the simplicity. This is :chefs_kiss: beautiful

2023-03-30 02:12 UTC, mikevanhemert commented on zarf.yaml
> +    # actions:
Recommend removing stale action

2023-03-30 02:12 UTC, mikevanhemert commented on zarf.yaml
>      prompt: true
Recommend adding description for this VAR

2023-03-30 02:12 UTC, mikevanhemert commented on zarf.yaml
> +    prompt: true
Recommend adding description for this VAR

2023-03-30 02:12 UTC, mikevanhemert commented on zarf.yaml
> +  - name: REF
Remove unused var

2023-03-30 02:12 UTC, mikevanhemert commented on zarf.yaml
> +  - name: DEPLOY_TYPE
Remove unused var

2023-04-05 20:30 UTC, docandrew approved these changes

2023-04-05 20:31 UTC, docandrew approved these changes

2023-04-05 20:40 UTC, mikevanhemert approved these changes

2023-04-05 20:41 UTC, merged